version: "3"

services:
  web:
    build: ./services/web
    image: "dev.master:30841/avidboard-web:${TAG}"
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./services/web:/usr/src/app
    container_name: avidboard-web
    depends_on:
      - accounts
      - kanban
  accounts:
    build: ./services/accounts
    image: "dev.master:30841/avidboard-accounts:${TAG}"
    command: npm run dev
    ports:
      - 5000:5000
    volumes:
      - ./services/accounts:/usr/src/app
    container_name: avidboard-accounts
    depends_on:
      - mongodb

  kanban:
    build: ./services/kanban
    image: "dev.master:30841/avidboard-kanban:${TAG}"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./services/kanban/app:/code/app
    container_name: avidboard-kanban
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=AdminPass22
    container_name: avidboard-mongodb
