apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: avidboard
build:
  tagPolicy:
    gitCommit:
      ignoreChanges: false
  artifacts:
    - image: dev.master:30841/avidboard-accounts
      context: services/accounts
      docker:
        dockerfile: dockerfile
    - image: dev.master:30841/avidboard-kanban
      context: services/kanban
      docker:
        dockerfile: dockerfile
    - image: dev.master:30841/avidboard-web
      context: services/web
      docker:
        dockerfile: dockerfile
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
profiles:
  - name: base
    deploy:
      kustomize:
        paths:
          - k8s/base
  - name: prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/prod
